[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "markitdown[docx,pdf]>=0.1.1",
    "mcp[cli]>=1.6.0",
    "pydantic>=2.11.3",
    "pytest>=8.3.5",
]
